name: PullReq

on:
  pull_request:
    branches: [main]

jobs:
  job1:
    name: j1
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"